spring:
  application:
    name: tasks
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: pass
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true